<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Departamentos Table -->
  <xs:element name="Departamentos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Departamento" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:int"/>
              <xs:element name="Nombre" type="xs:string"/>
              <xs:element name="UbicacionFisica" type="xs:string"/>
              <xs:element name="idResponsableArea" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Empleados Table -->
  <xs:element name="Empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:int"/>
              <xs:element name="Cedula" type="xs:string"/>
              <xs:element name="Nombre" type="xs:string"/>
              <xs:element name="SalarioMensual" type="xs:decimal"/>
              <xs:element name="idDepartamento" type="xs:int"/>
              <xs:element name="idPuesto" type="xs:int"/>
              <xs:element name="idNomina" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Puestos Table -->
  <xs:element name="Puestos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Puesto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:int"/>
              <xs:element name="Nombre" type="xs:string"/>
              <xs:element name="NivelDeRiesgo" type="xs:short"/>
              <xs:element name="MinimoSalario" type="xs:decimal"/>
              <xs:element name="MaximoSalario" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- TiposDeIngreso Table -->
  <xs:element name="TiposDeIngreso">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TipoDeIngreso" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:int"/>
              <xs:element name="Nombre" type="xs:string"/>
              <xs:element name="idEmpleado" type="xs:int"/>
              <xs:element name="Estado" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
